### ISSUE TITLE
README Needs a Ton of Love

### ISSUE THREAD

**Issue by SteveFeldman** [calisven/BalitmoreTowWebApp#2]
The README leaves a little to be desired. I'm glad to see you added the instructions for installing MongoDB, but there are more things you could do with the README to make the project more successful. I will put a few points below...
1. Installing MongoDB: It's great the have the link to someone else's instructions. You might as well put the steps in yourself. I personally have a Mac, so I did a Brew install, which made things a lot easier when all said in done. 
2. Ulimit issues on Mac after starting up MongoDB: I'm not sure if you ran into this issue or not, but based on what I experienced and then read on the Interweb, many Mongo users run out of file descriptors on start-up. I had to grant a minimum of 1000 file descriptors to the OS user I had running MongoDB.
3. Restoring the database: It looks like you made some changes here as well. When I originally used the instructions you provided, I received the following:

`
$ mongorestore —collection test —db cars cars.bson
2015-12-21T17:02:23.168-0500    too many positional arguments
2015-12-21T17:02:23.169-0500    try 'mongorestore --help' for more information
`

I ended up just running a very basic/simple command, but with my MongoDB already up and running:

`
$ mongorestore cars.bson
2015-12-21T17:03:45.438-0500    checking for collection data in cars.bson
2015-12-21T17:03:45.439-0500    reading metadata for test.cars from 
2015-12-21T17:03:45.440-0500    restoring test.cars from 
2015-12-21T17:03:46.095-0500    restoring indexes for collection test.cars from metadata
2015-12-21T17:03:46.095-0500    finished restoring test.cars (62158 documents)
2015-12-21T17:03:46.095-0500    done
`
1. Setting Up Tomcat: I would have expected instructions here as well. It wasn't hard to setup Tomcat as I run it on my machine all of the time. Assume your user hasn't done this before and hence, make it easier on the user so they can achieve greater success.
2. Other Information That's Missing:
- Instructions for building the War by hand: Another obvious and easy task, but no project is complete without complete instructions. I recommend adding this as soon as you can.
- Instructions for running the test suite: This too is super obvious, but should be part of the README to leave no stone unturned.
1. Going the Distance:

If I was going to take this project and make it better, I would make this incredibly simple for any user to get up and running to make it work. I would automate the entire process using Puppet, Chef or Ansible. I would have it built using a container technology like Vagrant or Docker. All the user would have to do is run a clone on the repository, then they would execute a single command which would do the following:
1. Install MongoDB
2. Import the archive file
3. Install Tomcat
4. Deploy the War to Tomcat
5. Startup Tomcat

Take a look at these Vagrant examples:
- https://github.com/j-panzer/vagrant-tomcat-mongodb
- https://github.com/rob-murray/vagrant-javadev-box

Here are some Docker examples:
- https://github.com/garystafford/spring-music-docker/wiki/Build-and-Deploy-a-Java-Spring-MongoDB-Application-using-Docker (More of a HowTo)
- https://github.com/docker-library/tomcat

**Comment by calisven** [comment]
Completely overhauled the README page to include step by step instructions from pre-installation to deployment. Love the idea of adding Docker support; this will be added in the future.
