### ISSUE TITLE
Why Not Use Java's Date Class?

### ISSUE THREAD

**Issue by SteveFeldman** [calisven/BalitmoreTowWebApp#4]
In DataRestService.java it looks like you have defined dates/months as strings. Seems like a lot of unnecessary code when you could easily use Java's Date Class: https://docs.oracle.com/javase/7/docs/api/java/util/Date.html

**Comment by calisven** [comment]
Used the Java Calendar class to get mm/dd/yyyy String containing the first day of every month for a given input year. Made a function that takes an input year and returns an array of every month of that given year.
