### ISSUE TITLE
Locations of Buttons and General Thoughts on User Experience

### ISSUE THREAD

**Issue by SteveFeldman** [calisven/BalitmoreTowWebApp#5]
In reference to: BalitmoreTowWebApp/WebContent/static/angular-templates/charts.html
## Vehicle Towed Visualization

A couple of take-aways on this chart. I would probably give the user the option to show a stacked view of 2014/2015 by month, or show them 2014/2015 side by side for comparison purposes. 

The drop-down by years is really distracting. There has to be a cleaner/better location for that button. If you watch the page load, it actually shows the button, but has an empty checkbox as it asynchronously loads the data. I definitely clicked on the button prior to rendering the chart and it did nothing. I would recommend finding a new location for that widget.
## Vehicles Stolen by Year

At first I thought this was another visualization of Vehicles Towed, but then I noticed that your title says stolen. So your data set has both towed and stolen vehicle information? It would be good to get more information about the data set. The visuals are semi-descriptive. It may make sense to have a (?) icon or something similar which the user could click on to get a description and/or instructions for working with the data set.
## Tow Charge Average

Is this in dollars? What is the chart telling us? 
## Vehicle Search

I would put the button to the right of Model. 

I like that the data set works if I only specify Make. However, if I only select Model (leave Make blank), I don't get any warning messages. The search won't execute. 

Can vehicles stolen also be searched?

**Comment by calisven** [comment]
<h4>Vehicle Towed Visualization</h4>

<p>Removed the 2014/2015 dropdown option and now display 2014 and 2015 data side by side. Moved the 'ng-show' code to cover the entire page except for the title while loading. Empty content as a result is no longer shown while the database is being queried.</p>

<h4>Vehicles Stolen by Year</h4>

<p>Added a better description and title to show that the data displayed is showing the number of the vehicles towed by the city that were also reported stolen.</p>

<h4>Tow Charge Average</h4>

<p>Updated description to show that the chart displays the average dollar amount charged to a vehicle owner to release their vehicle from the tow yard</p>

<h4>Vehicle Search</h4>

<p>Moved the submit button to the right side of the model. Added AngularJS form validation to disable the submit button when a model is not entered, and gives a hint text in the event the user clears the make text out after typing in it. Stolen vehicle search can easily be searchable and can be added in a future update.</p>
